[workspace]
members = [".", "core", "derive"]

[workspace.package]
edition = "2024"
version = "1.6.0"
description = "Rust trait for constant `#[repr(T)]` conversions"
license = "Apache-2.0 OR BSL-1.0 OR MIT"
homepage = "https://github.com/AldaronLau/as_repr/releases"
repository = "https://github.com/AldaronLau/as_repr"
keywords = ["repr", "transmute", "as", "const", "cast"]
categories = ["no-std", "no-std::no-alloc", "rust-patterns"]
rust-version = "1.91"

[package]
name = "as_repr"
documentation = "https://docs.rs/as_repr"
readme = "README.md"
include = [
    "/LICENSE_APACHE",
    "/LICENSE_BOOST",
    "/LICENSE_MIT",
    "/README.md",
    "/src/*",
    "/examples/*",
]
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies.as_repr-core]
version = "=1.5.0"
#path = "core"

[dependencies.as_repr-derive]
version = "=1.5.0"
#path = "derive"
optional = true

[features]
"cmp" = ["as_repr-core/cmp"]
"float" = ["as_repr-core/float"]
"inherent" = ["as_repr-core/inherent"]
"int" = ["as_repr-core/int"]
"num" = ["as_repr-core/num"]
"ops" = ["as_repr-core/ops"]
